apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleet-server
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs:
      - get
      - create
      - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-server
  namespace: kube-logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fleet-server
subjects:
  - kind: ServiceAccount
    name: fleet-server
    namespace: kube-logging
roleRef:
  kind: ClusterRole
  name: fleet-server
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastic-agent
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources:
      - namespaces
      - pods
      - nodes
      - events
      - services
      - configmaps
      - nodes
      - nodes/metrics
      - nodes/proxy
      - nodes/stats
      - events
    verbs:
      - get
      - watch
      - list
  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs:
      - get
      - create
      - update
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
      - watch
      - list
  - apiGroups: ["extensions"]
    resources:
      - replicasets
    verbs: 
      - "get"
      - "list"
      - "watch"
  - apiGroups: ["apps"]
    resources:
      - statefulsets
      - deployments
      - replicasets
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elastic-agent
  namespace: kube-logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elastic-agent
subjects:
  - kind: ServiceAccount
    name: elastic-agent
    namespace: kube-logging
roleRef:
  kind: ClusterRole
  name: elastic-agent
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  namespace: kube-logging
  name: fleet-server
spec:
  version: 7.15.0
  kibanaRef:
    name: kibana
    namespace: kube-logging
  elasticsearchRefs:
    - name: elasticsearch
      namespace: kube-logging
  mode: fleet
  fleetServerEnabled: true
  deployment:
    replicas: 1
    podTemplate:
      spec:
        automountServiceAccountToken: true
        securityContext:
          runAsUser: 0
        serviceAccountName: fleet-server
        containers:
          - name: agent
            resources:
              limits:
                memory: 1024Mi
                cpu: 1000m
              requests:
                memory: 512Mi
                cpu: 100m
---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  namespace: kube-logging
  name: elastic-agent
spec:
  version: 7.15.0
  kibanaRef:
    name: kibana
    namespace: kube-logging
  fleetServerRef:
    name: fleet-server
    namespace: kube-logging
  mode: fleet
  daemonSet:
    podTemplate:
      spec:
        automountServiceAccountToken: true
        serviceAccountName: elastic-agent
        securityContext:
          runAsUser: 0
        containers:
          - name: agent
            resources:
              limits:
                memory: 300Mi
                cpu: 200m
              requests:
                memory: 300Mi
                cpu: 10m
            volumeMounts:
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
            - mountPath: /var/log/containers
              name: varlogcontainers
            - mountPath: /var/log/pods
              name: varlogpods
        volumes:
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
---
apiVersion: v1
kind: Service
metadata:
  name: apm
  namespace: kube-logging
spec:
  selector:
    agent.k8s.elastic.co/name: fleet-server
  ports:
    - protocol: TCP
      port: 8200
