apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-and-trace
  namespace: mtgml
  annotations:
    iam.gke.io/gcp-service-account: log-and-trace@cubeartisan.iam.gserviceaccount.com
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: mtgml-server
  name: mtgml-server
  namespace: mtgml
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
  selector:
    service: mtgml-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: mtgml-server
  name: mtgml-server
  namespace: mtgml
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      service: mtgml-server
  template:
    metadata:
      labels:
        service: mtgml-server
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: github-docker
      serviceAccountName: log-and-trace
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: topology.gke.io/zone
                labelSelector:
                  matchExpressions:
                    - key: service
                      operator: In
                      values:
                        - mtgml-server
      containers:
        - name: mtgml-server
          image: "ghcr.io/cubeartisan/mtgml:20220922-6"
          env:
            - name: MTGML_VERSION
              value: "20220922-6"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONTAINER_NAME
              value: "mtgml-server"
            - name: MTGML_AUTH_ENABLED
              value: "False"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MTGML_AUTH_TOKENS
              valueFrom:
                secretKeyRef:
                  name: mtgmlsecrets
                  key: MTGML_AUTH_TOKENS
          ports:
            - containerPort: 8000
              name: http
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 4Gi
            requests:
              memory: 4Gi
              cpu: 1400m
          livenessProbe:
            httpGet:
              path: /version
              port: http
              httpHeaders:
                - name: User-Agent
                  value: 'kube-liveness-probe'
            failureThreshold: 3
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /version
              port: http
              httpHeaders:
                - name: User-Agent
                  value: 'kube-readiness-probe'
            periodSeconds: 60
          startupProbe:
            httpGet:
              path: /version
              port: http
              httpHeaders:
                - name: User-Agent
                  value: 'kube-startup-probe'
            failureThreshold: 60
            periodSeconds: 5
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mtgml-server-vpa
  namespace: mtgml
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mtgml-server
  updatePolicy:
    updateMode: "Off"
