apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: mtgml
  name: mtgml-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mtgml-server
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
