apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: mtgml
  name: mtgml-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mtgml-server
  minReplicas: 1
  maxReplicas: 8
  targetCPUUtilizationPercentage: 75
