apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: mtgml
  name: mtgml-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mtgml-server
  minReplicas: 2
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 900
      policies:
        - type: Pods
          value: 1
          periodSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 900
      policies:
        - type: Pods
          value: 1
          periodSeconds: 150
