apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongo
spec:
  members: 1
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: "mongodb-agent"
              resources:
                limits:
                  cpu: 250m
                  memory: 500M
                requests:
                  cpu: 50m
                  memory: 500M
            - name: "mongod"
              resources:
                limits:
                  cpu: 1000m
                  memory: 4G
                requests:
                  cpu: 100m
                  memory: 1G
