apiVersion: apps/v1
kind: Deployment
metadata:
  name: cube-recommender
spec:
  template:
    spec:
      containers:
        - name: cube-recommender
          resources:
            limits:
              memory: 2Gi
              cpu: 1
            requests:
              memory: 1Gi
              cpu: 100m
