apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - global/00-namespaces.yaml
  - global/02-elasticsearch.kube.yaml
  - global/04-kibana.kube.yaml
  - global/09-elastic-agent.kube.yaml
  - ./prod
  - ./staging
  - global/50-kibana-ingress.kube.yaml