apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - global/00-namespaces.yaml
  - global/30-mtgml-server.kube.yaml
  - ./prod
  - ./staging
  - global/50-kibana-ingress.kube.yaml
