apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongo
spec:
  members: 3
  type: ReplicaSet
  version: "4.4.10"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: cubeartisan
      db: cubeartisan
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongodb-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: dbAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
    - name: beats
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongodb-beats-password
      roles:
        - name: clusterMonitor
          db: admin
      scramCredentialsSecretName: my-scram-beats
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: "mongodb-agent"
              resources:
                limits:
                  cpu: 25m
                  memory: 256Mi
                requests:
                  cpu: 25m
                  memory: 128Mi
            - name: "mongod"
              resources:
                limits:
                  cpu: 225m
                  memory: 2Gi
                requests:
                  cpu: 75m
                  memory: 1Gi
