apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongo
spec:
  members: 3
  type: ReplicaSet
  version: "4.4.10"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: cubeartisan
      db: cubeartisan
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongodb-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: dbAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
    - name: beats
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongodb-beats-password
      roles:
        - name: clusterMonitor
          db: admin
      scramCredentialsSecretName: my-scram-beats
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: "mongodb-agent"
              resources:
                limits:
                  memory: 64Mi
                requests:
                  cpu: 30m
                  memory: 64Mi
            - name: "mongod"
              resources:
                limits:
                  memory: 960Mi
                requests:
                  cpu: 70m
                  memory: 960Mi
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mongo-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mongo
  updatePolicy:
    updateMode: "Off"
