apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongo
spec:
  members: 3
  type: ReplicaSet
  version: "4.4.7"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: cubeartisan
      db: cubeartisan
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongodb-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: dbAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: "mongodb-agent"
              resources:
                limits:
                  cpu: 250m
                  memory: 500M
                requests:
                  cpu: 50m
                  memory: 500M
            - name: "mongod"
              resources:
                limits:
                  cpu: 2000m
                  memory: 4G
                requests:
                  cpu: 500m
                  memory: 4G
