apiVersion: v1
kind: ServiceAccount
metadata:
  name: log-and-trace
  annotations:
    iam.gke.io/gcp-service-account: log-and-trace@cubeartisan.iam.gserviceaccount.com
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "cubeartisan-backend-config"}'
  labels:
    name: cubeartisan
  name: cubeartisan
spec:
  ports:
    - port: 80
      targetPort: 5000
      name: http
      protocol: TCP
  selector:
    name: cubeartisan
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: cubeartisan
  name: cubeartisan
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      name: cubeartisan
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        name: cubeartisan
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: github-docker
      volumes:
        - name: carddatabase
          hostPath:
            path: /var/carddatabase
            type: DirectoryOrCreate
      serviceAccountName: log-and-trace
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: topology.gke.io/zone
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - cubeartisan
      containers:
        - name: cubeartisan
          image: "ghcr.io/cubeartisan/cubeartisan:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: DISCORD_URL
              value: "https://discord.gg/qWPjyACs32"
            - name: DOWNTIME_ACTIVE
              value: "false"
            - name: CUBEARTISAN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cubeartisansecrets
                  key: CUBEARTISAN_API_KEY
            - name: EMAIL_CONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cubeartisansecrets
                  key: EMAIL_CONFIG_PASSWORD
            - name: EMAIL_CONFIG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cubeartisansecrets
                  key: EMAIL_CONFIG_USERNAME
            - name: LISTEN_ADDR
              value: "0.0.0.0"
            - name: MONGODB_DBNAME
              value: "cubeartisan"
            - name: MONGODB_HOST
              value: "mongo-svc"
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-password
                  key: password
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_REPLICASET
              value: mongo
            - name: MONGODB_USER
              value: cubeartisan
            - name: MTGML_SERVER
              value: "https://mtgml.cubeartisan.net/"
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "5000"
            - name: SESSION
              valueFrom:
                secretKeyRef:
                  name: cubeartisansecrets
                  key: SESSION
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: cubeartisansecrets
                  key: SESSION_SECRET
            - name: SITE_HOSTNAME
              value: <ENV>
            - name: SITE_NAME
              value: CubeArtisan
            - name: SITE_ROOT
              value: https://<ENV>
            - name: SITE_VERSION
              valueFrom:
                configMapKeyRef:
                  name: cubeartisan-version
                  key: TAG
            - name: SOURCE_REPO
              value: https://github.com/CubeArtisan/cubeartisan
            - name: SUPPORT_EMAIL
              value: support@cubeartisan.net
            - name: SUPPORT_EMAIL_FROM
              value: CubeArtisan Support Team <support@cubeartisan.net>
            - name: TELEMETRY
              value: 'true'
          ports:
            - containerPort: 5000
              name: http
          resources:
            limits:
              memory: 3Gi
            requests:
              memory: 3Gi
              cpu: 100m
          livenessProbe:
            httpGet:
              path: /version
              port: http
              httpHeaders:
                - name: User-Agent
                  value: 'kube-liveness-probe'
            failureThreshold: 1
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /version
              port: http
              httpHeaders:
                - name: User-Agent
                  value: 'kube-readiness-probe'
            periodSeconds: 60
          startupProbe:
            httpGet:
              path: /version
              port: http
              httpHeaders:
                - name: User-Agent
                  value: 'kube-startup-probe'
            failureThreshold: 60
            periodSeconds: 5
          volumeMounts:
            - mountPath: /CubeArtisan/server/private
              name: carddatabase
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: cubeartisan-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cubeartisan
  updatePolicy:
    updateMode: "Off"
