apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: cubeartisan-frontend-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: cubeartisan-backend-config
spec:
  timeoutSec: 3600
  connectionDraining:
    drainingTimeoutSec: 3600
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 600
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: true
    cacheMode: USE_ORIGIN_HEADERS
    negativeCaching: false
    requestCoalescing: true
  customRequestHeaders:
    headers:
    - "X-Client-Region:{client_region}"
    - "X-Client-City:{client_city}"
    - "X-Client-CityLatLong:{client_city_lat_long}"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cubeartisan-ingress
  annotations:
    networking.gke.io/v1beta1.FrontendConfig: cubeartisan-frontend-config
    networking.gke.io/managed-certificates: cubeartisan-cert
    kubernetes.io/ingress.class: gce
spec:
  rules:
    - host: <ENV>
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: cubeartisan
                port:
                  number: 80
