apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cubeartisan
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cubeartisan
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 150
    scaleUp:
      stabilizationWindowSeconds: 180
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mongodb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mongo
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cubeartisan
spec:
  minAvailable: 1
  selector:
    matchLabels:
      name: cubeartisan
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mongo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: mongo-svc
