apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cubeartisan
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cubeartisan
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mongodb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mongo
  minReplicas: 3
  maxReplicas: 8
  targetCPUUtilizationPercentage: 80
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cubeartisan
spec:
  minAvailable: 1
  selector:
    matchLabels:
      name: cubeartisan
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mongo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: mongo-svc
