name: Deploy to Staging
on:
  repository_dispatch:
    types:
      - deploy_staging
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the docker image.'
        required: true
      repository:
        description: 'Repository with the docker image.'
        required: true
        default: 'ghcr.io/cubeartisan'
env:
  PROJECT_ID: cubeartisan
  GKE_CLUSTER: cubeartisan
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: cubeartisan
jobs:
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Tag and Repository Owner from Workflow Dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          echo "REPOSITORY=${{ github.event.inputs.repository }}" >> $GITHUB_ENV
      - name: Get Tag and Repository Owner from Repository Dispatch
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          echo "TAG=${{ github.event.client_payload.tag }}" >> $GITHUB_ENV
          echo "REPOSITORY=${{ github.event.client_payload.repository }}" >> $GITHUB_ENV
      - name: Show tag and repo
        run: 'echo "REPOSITORY: $REPOSITORY" && echo "TAG: $TAG"'
      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
      - name: Get the GKE credentials for Deployment
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ${GITHUB_WORKSPACE}/kustomize
      - name: Update Image Tag and Version
        run: |-
          cd ${GITHUB_WORKSPACE}/staging
          ${GITHUB_WORKSPACE}/kustomize edit set image "$REPOSITORY/cubeartisan:$TAG"
          ${GITHUB_WORKSPACE}/kustomize edit set image "$REPOSITORY/cubeartisan-jobs:$TAG"
          kubectl create configmap cubeartisan-version -n cubeartisan-staging --from-literal TAG=$TAG -o yaml --dry-run=client > 44-cubeartisan-version.kube.yaml
      - name: Commit Changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Update staging deployment.'
          default_author: github_actions
          add: 'staging/44-cubeartisan-version.kube.yaml staging/kustomization.yaml'
      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |-
          cd ${GITHUB_WORKSPACE}
          kubectl replace -f staging/44-cubeartisan-version.kube.yaml || kubectl apply -f staging/44-cubeartisan-version.kube.yaml
          ${GITHUB_WORKSPACE}/kustomize build staging | kubectl apply -f -
      - name: Check Deployment
        run: |-
          kubectl rollout status -n cubeartisan-staging deployment/$DEPLOYMENT_NAME --timeout=600s
          kubectl get -n cubeartisan-staging services -o wide